pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    environment {
        SSH_PRIVATE_KEY = credentials('ab1ed2fc-ffdc-4b71-b710-476ae9705f3b')
        VM_IP = '20.224.162.44'
        VM_USER = 'azureuser'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/HarshOnCloud/hardcodedcompany.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
         stage('Update Packages') {
            steps {
                sh 'npm update'
            }
        }

        stage('Lint and Fix') {
            steps {
                sh 'npm run lint -- --fix'
            }
        }

        stage('Prettier Fix') {
            steps {
                sh 'npm run prettier -- --write .'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }
         stage('Build') {
            steps {
                // Navigate to the specific folder
                dir('dashboard/starter-example') {
                    // Perform the build (adjust command as needed)
                    sh 'npm install --legacy-peer-deps'
                    sh 'npm run build'
                }
            }
        }

       
        stage('Archive Artifacts') {
            steps {
                
                archiveArtifacts artifacts: 'dashboard/starter-example/.next/**', allowEmptyArchive: true
                sh 'ls -la dashboard/starter-example/.next'
            }
        }
        stage('Login to Azure') {
            steps {
                script {
                    sshagent(['ab1ed2fc-ffdc-4b71-b710-476ae9705f3b']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${env.VM_USER}@${env.VM_IP} "echo 'Logged in successfully'"
                    """
                }
            }
        }
        }
        stage('Deploy to Azure VM') {
            steps {
                script {
                    def resourceGroup = 'Harshvardhan'
                    def vmName = 'VM1'
                    def vmIP = '20.224.162.44'
                    
                    sshagent(['ab1ed2fc-ffdc-4b71-b710-476ae9705f3b']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${env.VM_USER}@${env.VM_IP} "echo 'Logged in successfully'"
                    az login
                    az account set --subscription c23fda47-c4d8-4460-bebe-412d27288d0c
                    az vm run-command invoke \
                        --command-id RunShellScript \
                        --name ${vmName} \
                        --resource-group ${resourceGroup} \
                        --scripts '
                        # Stop the existing application
                        sudo systemctl stop nginx

                        # Remove old application files
                        sudo rm -rf /var/www/html/*

                        # Copy new build files to the VM
                        scp -r dashboard/starter-example/.next/* azureuser@${vmIP}:/var/www/html/

                        # Start the application (Nginx)
                        sudo systemctl start nginx
                        '
                    """
                    }
                                    }
            }
        }
        stage('Health Check') {
            steps {
                script {
                    def healthCheckUrl = "http://${VM_IP}/health"
                    def response = sh(script: "curl -s -o /dev/null -w '%{http_code}' ${healthCheckUrl}", returnStdout: true).trim()

                    if (response != '200') {
                        error "Health check failed with response code: ${response}"
                    } else {
                        echo "Health check passed."
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
